CREATE TABLE account (
  _id SERIAL PRIMARY KEY,
  id VARCHAR (100) UNIQUE NOT NULL,
  first_name VARCHAR (100) NOT NULL,
  last_name VARCHAR (100) NOT NULL,
  email VARCHAR (254) UNIQUE NOT NULL,
  phone VARCHAR (50) UNIQUE NOT NULL,
  role VARCHAR (100) NOT NULL
);
